### PR TITLE
Fix streaming route

### PR DESCRIPTION
**Pull request by hinricht**
Until now, only /api/v1/streaming/ was routed to the streaming pod, while /api/v1/streaming/* was falsely routed to the web pod, which returned 404 for each request.
Now everything below /api/v1/streaming will reach the streaming pod.

Fixes: #36

### CODE REVIEW

**Comment by renchap** [comment]
Thanks! Could you please update your PR to not bump the Chart version?

**Review by renchap — CHANGES_REQUESTED** [review]
Thanks! Could you please update your PR to not bump the Chart version?

**Comment by hinricht** [comment]
@renchap Done!

**Review by renchap — APPROVED** [review]
Thanks!

**Pull request merged**
